source      : ./docs/source
destination: ./docs/_site

# Site settings
title: EC4py Package
author:
  name: Gustav Wiberg
  email: info@nordicec.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
#remote_theme: jekyll/minima
#remote_theme: pages-themes/minimal@v0.2.0
remote_theme: just-the-docs/just-the-docs
#theme: jekyll-theme-minima
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap

#  - docs/index.rst

defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false