# Site settings
title: Great New Blog Title
author:
  name: Gustav Wiberg
  email: info@nordicec.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-rst
include:
  - index.rst
  - docs/index.rst

defaults:
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false