name: 3. Upload Python Package to PyPi

on:
  workflow_dispatch:
     
jobs:
  build_release_job:
    uses: ./.github/workflows/build_release.yml
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore
    
